### ISSUE TITLE
S20 G988N Compatibility problems

### ISSUE THREAD

**Issue by j0912H97** [Jimbo77/Jimbok_common_sm8250-R#4]
Equipment G988N
Android version 11
system version one ui 3.0
Magisk version 21.4 21407
riru core version 23.4
Eedxposed version 0520 4672
lsposed version 0520 5071
I am using "thanox "In the case of this app
The module cannot be activated normally
Software prompt has been activated successfully
But the framework manager prompts and did not activate successfull
When I entered the app, I didn’t see it
Log I have provided to magisk edxposed lsposed thanox
But I also want to provide you with the log to make your kernel more perfect, hope it will help you
[Log.zip](https://github.com/Jimbo77/Jimbok_common_sm8250-R/files/5899121/Log.zip)

**Comment by Jimbo77** [comment]
The issue does not seem to be Kernel related. EdXposed can be loaded with the current state of the Kernel, if a module does not work please check with the module owner for compatibility with latest Samsung OS releases.
